---
- name: ensure timezone is set in apache2 php.ini
  lineinfile: dest=/etc/php/7.1/apache2/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'

- name: enabling opcache
  lineinfile: dest=/etc/php/7.1/apache2/php.ini
              regexp=';?opcache.enable=\d'
              line='opcache.enable=1'
