---
# application tasks to be customized and to run after the main provision

- name: Display Errors in /etc/php5/apache2/php.ini
  shell: sed -i -e 's/^display_errors =.*/display_errors = On/g' /etc/php5/apache2/php.ini
  sudo: yes

- name: Display Errors in /etc/php5/cli/php.ini
  shell: sed -i -e 's/^display_errors =.*/display_errors = On/g' /etc/php5/cli/php.ini
  sudo: yes

- name: Display Errors in /etc/php5/fpm/php.ini
  shell: sed -i -e 's/^display_errors =.*/display_errors = On/g' /etc/php5/fpm/php.ini
  sudo: yes

# Error Reporting
- name: Error Reporting in /etc/php5/apache2/php.ini
  shell: sed -i -e 's/^error_reporting =.*/error_reporting = E_ALL/g' /etc/php5/apache2/php.ini
  sudo: yes

- name: Error Reporting in /etc/php5/cli/php.ini
  shell:  sed -i -e 's/^error_reporting =.*/error_reporting = E_ALL/g' /etc/php5/cli/php.ini
  sudo: yes

- name: Display Errors in /etc/php5/fpm/php.ini
  shell: sed -i -e 's/^error_reporting =.*/error_reporting = E_ALL/g' /etc/php5/fpm/php.ini
  sudo: yes

- name: Reload all
  shell: service php5-fpm restart && service apache2 restart
  sudo: yes
